### ISSUE TITLE
Update 'signxml' Python library

### ISSUE THREAD

**Issue by jtrh** [fyntex/lib-cl-sii-python#130]
- [x] Review the [changelog](https://github.com/XML-Security/signxml/blob/v2.8.0/Changes.rst) of the library.
- [x] Find out the status of the library's use of `defusedxml`.
  - https://github.com/XML-Security/signxml/commit/83c05fbfdc9efbea0ddc13cd490b423bb772ef5d
- [x] Update package version in:
  - `setup.py`
  - `requirements/base.txt`
- [x] For each project of our organization that depends on `cl-sii`, create an issue to track the updating of its version of `cl-sii` to one that depends on the updated `signxml`.
  - [x] https://github.com/fyntex/lib-cl-sii-api-python/issues/160
  - [x] https://github.com/fyntex/fd-cl-data/issues/496

**Comment by glarrain** [comment]
I'm not sure but I think `zeep` might have something do with this as well
- https://github.com/mvantellingen/python-zeep
- https://docs.python-zeep.org
- https://pypi.org/project/zeep/
